from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field


class KodaWikiState(BaseModel):
    """LangGraph State representation across KodaWiki agents."""

    target_dir: str = ""
    user_prompt: str = ""
    wiki_context: str = ""

    # Plan generated by Planner Agent
    plan_steps: List[str] = Field(default_factory=list)
    target_files: List[str] = Field(default_factory=list)

    # Coding & Testing state
    current_step: int = 0
    code_changes: Dict[str, str] = Field(
        default_factory=dict
    )  # rel_path -> new_content
    test_result: Optional[Dict[str, Any]] = None

    # Retry loop tracking
    retry_count: int = 0
    max_retries: int = 3
    is_complete: bool = False
    error_message: str = ""
